apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
  labels:
    app: bot-app
spec:
  selector:
    matchLabels:
      app: bot-app 
  replicas: 2
  template:
    metadata:
      labels:
        app: bot-app
    spec:
      containers:
      - name: customer-app
        image: tomeroz802/tomer-bot-test
        imagePullPolicy: Always